spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/querydsl
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: querydsl
    password: querydsl

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        #show_sql: true
logging.level :
  org.hibernate.SQL : debug
  org.hibernate.type : trace
